# Generated by Django 5.2.7 on 2025-11-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('onlynamemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.onlynamemodel')),
            ],
            bases=('catalog.onlynamemodel',),
        ),
        migrations.AddField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(to='catalog.collection'),
        ),
    ]
